name: synchronize

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Synchronize
        run: |
          repository="https://github.com/MR-Addict/Doc-Share.git"

          file_content=$(cat .hash)
          latest_commit=$(git ls-remote $repository HEAD | awk '{ print $1 }')

          if [ $file_content = $latest_commit ]; then
            echo "Abort synchronizing"
          else
            echo $latest_commit > .hash
            git clone --depth 1 $repository
            rm -rf 电子组 && mkdir 电子组 && rm Doc-Share/src/SUMMARY.md && mv Doc-Share/src/* 电子组 && rm -rf Doc-Share
            git config --global user.name "MR-Addict"
            git config --global user.email "MR-Addict@qq.com"
            git add . && git commit -m "ci: synchronize from MR-Addict/Doc-Share" && git push origin main
          fi
